---
# https://github.com/hashicorp/vagrant/tree/master/keys
- name: create ~/.ssh directory for virtual machine user
  file: path="{{ item.home }}/.ssh" state=directory mode=0700
  with_items: "{{ users }}"

- name: copy vagrant private key to virtual machine user
  copy:
    src: "{{ lookup('env','HOME') + '/.vagrant.d/insecure_private_key' }}"
    dest: "{{ item.home }}/.ssh/id_rsa"
    owner: "{{ item.user }}"
    mode: 0600
  with_items: "{{ users }}"

- name: set vagrant default authorized key
  authorized_key: user="{{ item.user }}" state=present key="{{lookup('file', 'vagrant.pub') }}"
  with_items: "{{ users }}"
